format_version: v1.0
type: UniqueComponent
attributes: {id: legato_gfx_mxt_cpro}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DisplayInterface}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SPI 4-Line}
  - type: Combo
    attributes: {id: currDisplayInterface}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_mxt_cpro, value: SPI 4-Line}
- type: ElementPosition
  attributes: {x: '176', y: '81', id: legato_gfx_mxt_cpro}
